// done with Gemini, 14-Sep-2025
// first prompt: generate one hundred object descriptions appropriate for
//               use in the game 'robotfindskitten'
// second prompt: do this task again, but (a) ensure that each
//                generated string is less than 50 characters in length;
//                (b) format the result as a C variable declaration that
//                contains the strings in an array.

/*
 * An array of 100 Non-Kitten-Item (NKI) descriptions
 * for robotfindskitten. Each string is < 50 chars.
 */
const char *nki_descriptions[] = {
    "A dusty paperclip.",
    "A half-eaten bag of chips.",
    "The sensation of déjà vu.",
    "A single, unmatched sock.",
    "A burnt-out lightbulb.",
    "A hopelessly tangled phone cord.",
    "A puddle of mysterious liquid.",
    "A wobbly three-legged stool.",
    "An ancient Yellow Pages book.",
    "A small pile of sawdust.",
    "A fussy USB cable.",
    "The abstract concept of Tuesday.",
    "A completely drained battery.",
    "A sticky spot on the floor.",
    "An aggressive-looking fern.",
    "A single, petrified Cheerio.",
    "A ball of lint and human hair.",
    "A losing lottery ticket.",
    "A floppy disk labeled 'GAMES'.",
    "A vague sense of impending doom.",
    "An empty, greasy pizza box.",
    "A crumpled, unreadable sticky note.",
    "A single, loose screw.",
    "A judgmental rubber duck.",
    "A squeaky piece of styrofoam.",
    "A dead pixel in your visual sensor.",
    "A commemorative bicentennial plate.",
    "A forgotten ice cube, melting.",
    "An old, forgotten bottle cap.",
    "A coffee cup with a lipstick stain.",
    "A single strand of festive tinsel.",
    "The faint, ghostly smell of cinnamon.",
    "A fragment of a forgotten song.",
    "A lone chess pawn.",
    "An unplugged-in lamp.",
    "A spork, a tool of indecision.",
    "A slightly deflated balloon.",
    "An expired dry cleaning coupon.",
    "A stray Lego brick. A menace.",
    "A warm spot on the floor.",
    "A length of uncooperative garden hose.",
    "A book titled 'Advanced VCR Repair'.",
    "A quivering, gelatinous cube.",
    "A fused mass of old rubber bands.",
    "A pen that has run out of ink.",
    "The urge to defragment a hard drive.",
    "A dusty dial-up modem, blinking.",
    "A remote missing its battery cover.",
    "A small, perfectly smooth stone.",
    "A melted cassette tape.",
    "A small spacetime anomaly.",
    "A plastic fork with a missing tine.",
    "Junk mail for 'Current Resident'.",
    "A patch of hideous shag carpeting.",
    "An errant breadcrumb.",
    "A 404 error in physical form.",
    "A button from a stranger's coat.",
    "The wrong type of screwdriver.",
    "A suspiciously sticky ice cream scoop.",
    "A single playing card: three of clubs.",
    "A user manual for a product you don't own.",
    "A tangled collection of bread ties.",
    "A glass eye. It's watching you.",
    "An empty jar of mayonnaise.",
    "A string too short to be useful.",
    "A hairball. Not from a kitten.",
    "A disturbing inkblot.",
    "A glob of congealed bacon grease.",
    "An old TV antenna.",
    "A small, ceramic figurine of a sad clown.",
    "A smudged 'Hello, my name is' tag.",
    "A packet of silica gel. DO NOT EAT.",
    "A broken piece of a terracotta pot.",
    "A wad of previously-chewed gum.",
    "A single, brown banana peel.",
    "An Allen key for some forgotten furniture.",
    "The low, silent hum of a refrigerator.",
    "The dusty remains of a dead moth.",
    "Novelty sunglasses with one lens missing.",
    "A memory of a dial-up modem sound.",
    "A pile of unfiled TPS reports.",
    "A used and dried-out tea bag.",
    "A mysterious stain on the ceiling.",
    "A tightly wadded ball of aluminum foil.",
    "A cracked CD jewel case.",
    "An avocado pit suspended in water.",
    "A business card for a psychic detective.",
    "The source code for this program.",
    "A dust bunny of unusual size.",
    "A single, wooden golf tee.",
    "A single, unclaimed mitten.",
    "A fuzzy six-sided die.",
    "A small tear in the upholstery.",
    "An empty roll of toilet paper.",
    "A political campaign button from a loser.",
    "A plastic army man, frozen in a pose.",
    "A single, metallic staple.",
    "A mild sense of disappointment.",
    "A phone book for a city you've never seen.",
    "A Klein bottle. You are inside and outside."
};
